### ISSUE TITLE
can't configure 

### ISSUE THREAD

**Issue by bashcode** [Galarzaa90/GuildWatcher#9]
2018-11-19 22:17:13,654:ERROR: Malformed config.json file.

**Comment by Galarzaa90** [comment]
I will need to see the config.json file

**Comment by bashcode** [comment]
{
  "__comment__": "To use this file, rename it to config.json",
  "webhook_url": "https://canary.discordapp.com/api/webhooks/514242920182972416/QNprfG2kzu3KxxxKGqBLMDoHkgJXYtPQEFM7UuOLYrltr-NKcgnv8n2xxxxx"
  "guilds": [
    {"name": "New era", "override_image": true},
    {"name": "Insane"},
    {"name": "Reappers"}
  ]
}

Result: 2018-11-20 12:07:24,802:ERROR: Malformed config.json file.

**Comment by Galarzaa90** [comment]
You're missing a comma at the end of "webhook_url"

You can always test json files here: https://jsonlint.com/

This would be the corrected file:
```json
{
	"comment": "To use this file, rename it to config.json",
	"webhook_url": "https://canary.discordapp.com/api/webhooks/514242920182972416/QNprfG2kzu3KxxxKGqBLMDoHkgJXYtPQEFM7UuOLYrltr-NKcgnv8n2xxxxx",
	"guilds": [{
			"name": "New era",
			"override_image": true
		},
		{
			"name": "Insane"
		},
		{
			"name": "Reappers"
		}
	]
}
```

**Comment by bashcode** [comment]
Thanks mate is working now.

I have seen that some guilds that have an space for example 'New era' are not accepted by the app, the guild exists in tibia.com.
